import assert from 'node:assert/strict';
import fs from 'node:fs';
const api = fs.readFileSync(new URL('../api/ai-workroom.js', import.meta.url), 'utf8');
const migration = fs.readFileSync(new URL('../supabase/migrations/20260815221500_ai_workroom.sql', import.meta.url), 'utf8');
assert.match(migration, /ai_workroom_threads/); assert.match(migration, /ai_workroom_messages/); assert.match(migration, /enable row level security/i);
assert.match(migration, /ai_workroom_projects/); assert.match(migration, /ai_workroom_sources/); assert.match(migration, /pinned boolean/);
assert.match(api, /requireUser/); assert.match(api, /HIVELOGIC_WORKROOM_AGENT_SECRET/); assert.match(api, /agent_update/); assert.match(api, /send_message/);
assert.match(api, /create_project/); assert.match(api, /pin_thread/); assert.match(api, /dashboard/);
assert.match(api, /import_history/); assert.match(api, /claude_code/); assert.match(api, /manager_self_test/);
assert.match(api, /\\u0000-\\u0008/, 'history imports must strip PostgreSQL-invalid null and control characters');
assert.match(api, /cleanText\(await response\.text\(\)\)/, 'database failures must retain a bounded diagnostic detail');
assert.match(api, /grok/); assert.match(api, /reina/); assert.match(api, /record_lesson/); assert.match(api, /learningDashboard/);
assert.match(api, /intendedPurpose/); assert.match(api, /observedBehavior/); assert.match(api, /valueAssessment/);
assert.match(api, /HIVELOGIC_WORKROOM_OWNER_ID/); assert.match(api, /bridgeAuthorized/);
assert.doesNotMatch(api, /auth\.forbidden/); assert.doesNotMatch(api, /auth\?\.ok/);
assert.match(api, /: auth\.id/); assert.doesNotMatch(api, /auth\.staff/);
assert.match(api, /create_budget_policy/); assert.match(api, /record_model_usage/); assert.match(api, /costDashboard/);
assert.doesNotMatch(api, /\/rest\/v1\//, 'supabaseRequest already supplies the REST prefix');
const costMigration = fs.readFileSync(new URL('../supabase/migrations/20260815233000_ai_workroom_cost_controls.sql', import.meta.url), 'utf8');
assert.match(costMigration, /ai_workroom_budget_policies/); assert.match(costMigration, /ai_workroom_model_usage/); assert.match(costMigration, /enable row level security/i);
const historyMigration = fs.readFileSync(new URL('../supabase/migrations/20260816015818_workroom_history_retention.sql', import.meta.url), 'utf8');
const guard = fs.readFileSync(new URL('../api/_lib/guard.js', import.meta.url), 'utf8');
assert.match(guard, /'\/api\/ai-workroom'/, 'the global edge guard must let the Workroom machine credential reach the handler');
assert.match(historyMigration, /ai_workroom_import_checkpoints/);
assert.match(historyMigration, /source_message_id/);
assert.match(historyMigration, /unique \(thread_id, source, source_message_id\)/i);
assert.match(historyMigration, /enable row level security/i);
assert.match(api, /async function dbAll/);
assert.match(api, /resolution=ignore-duplicates/);
assert.match(api, /source_conversation_id/);
assert.doesNotMatch(api, /order=created_at\.asc&limit=300/);
assert.match(api, /headers: req\?\.headers \|\| \{\}/, 'internal Council dispatch must preserve request authorization headers');
assert.match(api, /maxTokensPerResponse: 4_000/, 'Workroom must leave enough output room for a complete structured Council answer');
assert.match(api, /maxCostCents: 100/, 'Workroom must stay within the production Council cost ceiling');
assert.match(api, /createCouncilHandler\(\{\s*minimumParticipants: 1,/, 'Workroom must preserve valid answers when one Council vendor is unavailable');
assert.match(api, /requireStaff: async \(\) => /, 'Workroom must resolve Council identity from the already-authenticated caller (bridge or user), not re-derive it from headers that the bridge path never carries');
assert.match(api, /bridgeAuthorized \? 'admin' : auth\.role/, 'the agent\/desktop bridge always acts as the configured admin owner; a signed-in user keeps their real role so a non-admin still gets rejected');
assert.match(api, /dispatchCouncil\(req, id, userMessage\.id, userMessage\.body, conversation, ownerId, bridgeAuthorized \? 'admin' : auth\.role\)/, 'dispatchCouncil must receive the already-resolved owner and role instead of re-deriving them from request headers');
assert.match(api, /degraded_providers/, 'Workroom must disclose degraded provider participation');
console.log('AI Workroom contract tests passed');
