import assert from 'node:assert/strict';
import fs from 'node:fs';
const api = fs.readFileSync(new URL('../api/workroom.js', import.meta.url), 'utf8');
const migration = fs.readFileSync(new URL('../supabase/migrations/20260815234500_workroom_autonomy.sql', import.meta.url), 'utf8');
const hardGate = fs.readFileSync(new URL('../supabase/migrations/20260816123422_enforce_hard_completion_gate.sql', import.meta.url), 'utf8');
const workflow = fs.readFileSync(new URL('../.github/workflows/hardened-completion-gate.yml', import.meta.url), 'utf8');
for (const name of ['workroom_tasks', 'workroom_events', 'workroom_evidence']) assert.match(migration, new RegExp(name));
assert.match(migration, /enable row level security/i);
for (const action of ['create_task', 'add_evidence', 'post_review', 'review_requested', 'gate_passed', 'cost_escalated']) assert.match(api, new RegExp(action));
assert.match(api, /HIVELOGIC_WORKROOM_AGENT_SECRET/);
assert.match(api, /requireUser/);
assert.match(api, /model_tier/);
assert.match(api, /grok/); assert.match(api, /reina/);
assert.doesNotMatch(api, /\/rest\/v1\//, 'supabaseRequest already supplies the REST prefix');
assert.match(api, /evaluateTaskCompletion/);
assert.match(api, /Work is NOT DONE\. The completion gate failed/);
for (const type of ['diff', 'test', 'crawler', 'preview', 'review', 'deployment']) assert.match(hardGate, new RegExp(`\\('${type}'\\)`));
assert.match(hardGate, /workroom_tasks_verified_done_check/);
assert.match(hardGate, /workroom_tasks_completion_gate/);
assert.match(hardGate, /workroom_evidence_revokes_completion/);
assert.match(hardGate, /status = 'review'[\s\S]*where status = 'done'/);
assert.match(hardGate, /security invoker/);
assert.match(hardGate, /verified receipt is immutable/);
assert.match(hardGate, /evidence_sequence bigint generated always as identity/);
assert.match(api, /order=evidence_sequence\.asc/);
assert.match(hardGate, /workroom_tasks_read_owner/);
assert.match(hardGate, /revoke insert, update, delete on public\.workroom_tasks from anon, authenticated/);
assert.match(hardGate, /assigned_agent[\s\S]*'grok'[\s\S]*'reina'/);
assert.match(hardGate, /latest\.evidence_type = 'diff'[\s\S]*\[0-9a-f\]\{7,40\}/);
assert.match(hardGate, /latest\.evidence_type in \('preview', 'deployment'\)[\s\S]*\^https:\/\//);
assert.match(hardGate, /order by e\.evidence_sequence desc[\s\S]*independent review is required/);
assert.match(hardGate, /receipt source revision does not match verified diff evidence/);
assert.match(hardGate, /receipt deployment URL does not match verified deployment evidence/);
assert.match(hardGate, /revoke execute on function public\.workroom_enforce_completion_gate\(\) from public, anon, authenticated/);
assert.match(workflow, /pull_request:/);
assert.match(workflow, /push:[\s\S]*branches: \[main\]/);
assert.match(workflow, /Full regression \(required for DONE\)/);
assert.match(workflow, /npm ci[\s\S]*npm test/);
console.log('Workroom autonomy contract tests passed');
