import { createHash } from 'node:crypto';
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { trialBalance, verifyAuditChain, verifyPostedEntries } from './ledger.js';
import { accountsPayableAging, basisBalanceSheet, incomeStatement, salesTaxLiability, contractorTaxReport } from './reporting.js';
import { verifyControlAudit } from './controls.js';
import { detectExpenseDuplicates, verifyReconciliation } from './banking.js';
import { createZip, createXlsx, createSimplePdf } from './archive.js';

const amount = value => Math.round((Number(value) || 0) * 100) / 100;
const checksum = content => createHash('sha256').update(content).digest('hex');
const csvEscape = value => { const text = value == null ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replaceAll('"','""')}"` : text; };
const csv = (headers, rows) => [headers.join(','),...rows.map(row=>headers.map(header=>csvEscape(row[header])).join(','))].join('\r\n');
const rowsForWorkbook = (headers, rows) => [headers,...rows.map(row=>headers.map(header=>row[header]))];

export function closeReadiness({ system, expenses, companyId, throughDate, evidenceDocuments = [] }) {
  const company = system.ledger.companies[companyId]; if (!company) throw new Error('Company not found.'); const checks=[]; const add=(id,label,passed,detail,blocking=true)=>checks.push({id,label,passed,detail,blocking});
  const scopedExpenses=expenses.filter(expense=>expense.transactionDate<=throughDate); const trial=trialBalance(system.ledger,companyId,throughDate); const sheet=basisBalanceSheet(system.ledger,companyId,{throughDate,basis:company.basis}); const audit=verifyAuditChain(system.ledger); const posted=verifyPostedEntries(system.ledger,companyId); const control=verifyControlAudit(system.controls);
  add('closing_sequence','Closing date moves forward',!company.closingDate||throughDate>=company.closingDate,company.closingDate&&throughDate<company.closingDate?`The books are already closed through ${company.closingDate}. Use the stored package for this earlier period.`:`Closing through ${throughDate} preserves the existing closing date.`);
  add('trial_balance','Trial balance balances',trial.balanced,trial.balanced?'Debits equal credits.':`Difference ${amount(trial.totalDebits-trial.totalCredits).toFixed(2)}.`);
  add('balance_sheet','Balance sheet balances',sheet.balanced,sheet.balanced?'Assets equal liabilities plus equity.':`Difference ${sheet.difference.toFixed(2)}.`);
  add('ledger_audit','Ledger audit chain is intact',audit.valid,audit.valid?`${audit.records} audit records verified.`:`Audit break at ${audit.brokenAt}.`);
  add('posted_seals','Posted entries are unchanged',posted.valid,posted.valid?`${posted.checked} posted entries verified.`:`${posted.failures.length} posted entry seal failure(s).`);
  add('control_audit','Approval and QBO audit chain is intact',control.valid,control.valid?`${control.records} control records verified.`:`Control audit break at ${control.brokenAt}.`);
  const unknown=scopedExpenses.filter(expense=>expense.status==='unrecorded'||expense.allocations?.some(line=>line.ownerType==='unknown')); add('unknown_expenses','Every expense has an owner',unknown.length===0,unknown.length?`${unknown.length} expense(s) remain unrecorded.`:'No unknown expenses.');
  const evidenceIds=new Set(evidenceDocuments.map(document=>document.id)); const missingEvidence=scopedExpenses.filter(expense=>!expense.evidenceDocumentIds?.some(id=>evidenceIds.has(id))); add('supporting_evidence','Every expense has immutable supporting evidence',missingEvidence.length===0,missingEvidence.length?`${missingEvidence.length} expense(s) do not have stored evidence.`:'Every expense is linked to stored evidence.');
  const pendingApprovals=system.controls.approvals.filter(item=>item.status==='pending'&&scopedExpenses.some(expense=>expense.id===item.entityId)); add('approvals','All in-period expenses are approved',pendingApprovals.length===0,pendingApprovals.length?`${pendingApprovals.length} approval(s) remain.`:'No pending approvals.');
  const unposted=company.entries.filter(entry=>entry.date<=throughDate&&!['posted','voided'].includes(entry.status)); add('posting','All in-period journals are posted',unposted.length===0,unposted.length?`${unposted.length} journal(s) are not posted.`:'All journals are posted.');
  const duplicates=detectExpenseDuplicates(scopedExpenses).filter(item=>item.confidence>=.82); add('duplicates','Duplicate review is complete',duplicates.length===0,duplicates.length?`${duplicates.length} duplicate candidate(s) remain.`:'No unresolved duplicate candidates.');
  const rejectedExpenses=scopedExpenses.filter(expense=>expense.status==='needs_correction'); add('rejected_expenses','Rejected expenses are corrected',rejectedExpenses.length===0,rejectedExpenses.length?`${rejectedExpenses.length} rejected expense(s) need a corrected replacement.`:'No rejected expenses remain unresolved.');
  const unmatched=(company.bankTransactions||[]).filter(item=>item.postedDate<=throughDate&&!['matched','classified','excluded'].includes(item.status)); add('bank_matching','All bank and card activity is resolved',unmatched.length===0,unmatched.length?`${unmatched.length} bank/card transaction(s) are unresolved.`:'All imported bank and card activity is resolved.');
  const configuredReconciliationAccounts=Object.values(company.accounts||{}).filter(account=>account.reconciliationRequired===true||(!['Sales Tax Payable','Accounts Payable','Loan Payment Clearing'].includes(account.name)&&/(bank|card|checking|savings|operating|chase|amex)/i.test(account.name))).map(account=>account.id); const activeAccounts=[...new Set([...configuredReconciliationAccounts,...(company.bankTransactions||[]).filter(item=>item.postedDate<=throughDate).map(item=>item.accountId)])]; const unreconciled=activeAccounts.filter(accountId=>!(company.reconciliations||[]).some(item=>item.accountId===accountId&&item.status==='complete'&&item.endDate>=throughDate)); add('reconciliations','Every bank and card account is reconciled',unreconciled.length===0,unreconciled.length?`${unreconciled.length} account(s) lack a completed reconciliation through ${throughDate}.`:'Every bank and card account is reconciled.');
  const broken=(company.reconciliations||[]).filter(item=>item.endDate<=throughDate).filter(item=>{try{return !verifyReconciliation(system.ledger,companyId,item.id).valid}catch{return true}}); add('reconciliation_integrity','Completed reconciliations remain intact',broken.length===0,broken.length?`${broken.length} reconciliation snapshot(s) changed.`:'Reconciliation snapshots are intact.');
  const statements=(system.pendingStatements||[]).filter(item=>(item.endDate||item.createdAt?.slice(0,10)||'0000-00-00')<=throughDate&&item.status!=='complete'); const accountsWithoutStatement=activeAccounts.filter(accountId=>!(company.reconciliations||[]).some(item=>item.accountId===accountId&&item.status==='complete'&&item.endDate>=throughDate)&&!(system.pendingStatements||[]).some(item=>item.accountId===accountId&&item.endDate>=throughDate)); const statementBlockers=statements.length+accountsWithoutStatement.length; add('statements','Every bank and card statement is accounted for',statementBlockers===0,statementBlockers?`${statements.length} uploaded statement(s) remain incomplete and ${accountsWithoutStatement.length} account(s) have no statement coverage.`:'All required statements are processed.');
  const documentIntake=[...(system.documentInbox||[]),...(system.loans||[]),...(system.taxNotices||[]),...(system.payrollSummaries||[])].filter(item=>item.status!=='processed'&&item.status!=='complete'&&(item.transactionDate||item.statementDate||item.noticeDate||item.periodEnd||item.createdAt?.slice(0,10)||'0000-00-00')<=throughDate); const unreadEvidence=evidenceDocuments.filter(item=>!['extracted','processed'].includes(item.status)&&(item.created_at||item.createdAt||'0000-00-00').slice(0,10)<=throughDate); const documentBlockers=documentIntake.length+unreadEvidence.length; add('document_intake','Every uploaded document is entered or reviewed',documentBlockers===0,documentBlockers?`${documentIntake.length} document decision(s) and ${unreadEvidence.length} unreadable file(s) still need review.`:'Every uploaded document has been processed.');
  const tax=salesTaxLiability(system.sales||[],system.taxPayments||[],throughDate); add('sales_tax','Sales-tax jurisdictions are assigned',tax.unassigned===0,tax.unassigned?`$${tax.unassigned.toFixed(2)} of sales-tax liability is unassigned.`:'Sales-tax liabilities are assigned by state.');
  const contractors=contractorTaxReport(system.vendors||[],system.contractorPayments||[],{year:Number(throughDate.slice(0,4)),threshold:system.contractorThreshold||600}); add('contractors','Contractor tax records are complete',contractors.blockers.length===0,contractors.blockers.length?`${contractors.blockers.length} contractor tax blocker(s) remain.`:'Contractor tax records are ready.');
  const criticalAlerts=(system.automation?.alerts||[]).filter(item=>item.status==='active'&&item.severity==='critical'); add('automation_exceptions','No critical automation exceptions remain',criticalAlerts.length===0,criticalAlerts.length?`${criticalAlerts.length} critical automation exception(s) remain.`:'No critical automation exceptions.');
  const journalExpenseIds=new Set(company.entries.filter(entry=>entry.source==='expense'&&entry.date<=throughDate).map(entry=>entry.sourceId)); const orphanExpenses=scopedExpenses.filter(expense=>!journalExpenseIds.has(expense.id)); const orphanJournals=[...journalExpenseIds].filter(id=>!scopedExpenses.some(expense=>expense.id===id)); add('source_links','Expenses and journals are fully linked',orphanExpenses.length+orphanJournals.length===0,`${orphanExpenses.length} orphan expense(s), ${orphanJournals.length} orphan journal(s).`);
  const postedExpenseIds=company.entries.filter(entry=>entry.status==='posted'&&entry.source==='expense'&&entry.date<=throughDate).map(entry=>entry.sourceId); const accountsPayable=accountsPayableAging(expenses,{throughDate,postedExpenseIds}); const blockers=checks.filter(check=>check.blocking&&!check.passed); return {companyId,throughDate,basis:company.basis,ready:blockers.length===0,score:Math.round(checks.filter(check=>check.passed).length/checks.length*100),checks,blockers,summary:{expenses:scopedExpenses.length,postedEntries:company.entries.filter(entry=>entry.status==='posted'&&entry.date<=throughDate).length,unresolved:unknown.length+unmatched.length+pendingApprovals.length,trialBalance:trial,balanceSheet:sheet,accountsPayable,salesTax:tax,contractors}};
}

export function buildClosePackage({ system, expenses, companyId, throughDate, evidenceDocuments = [] }) {
  const readiness=closeReadiness({system,expenses,companyId,throughDate,evidenceDocuments}); if(!readiness.ready) throw new Error(`Period cannot close: ${readiness.blockers.map(item=>item.detail).join(' ')}`); const company=system.ledger.companies[companyId]; const basis=company.basis; const yearStart=`${throughDate.slice(0,4)}-01-01`; const pnl=incomeStatement(system.ledger,companyId,{startDate:yearStart,endDate:throughDate,basis}); const sheet=basisBalanceSheet(system.ledger,companyId,{throughDate,basis}); const trial=readiness.summary.trialBalance;
  const accounts=Object.values(company.accounts); const accountName=id=>accounts.find(account=>account.id===id)?.name||id; const posted=company.entries.filter(entry=>entry.status==='posted'&&entry.date<=throughDate).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
  const journalRows=posted.flatMap(entry=>entry.lines.map(line=>({'Journal No.':entry.id,'Journal Date':entry.date,'Account Name':accountName(line.accountId),'Description':line.memo||entry.description,'Debits':line.debit||'','Credits':line.credit||'','Name':line.dimensions?.ownerId||'','Class':line.dimensions?.ownerType||'','Location':line.dimensions?.taxState||''})));
  const ledgerRows=posted.flatMap(entry=>entry.lines.map(line=>({Date:entry.date,'Journal ID':entry.id,Account:accountName(line.accountId),Description:line.memo||entry.description,Debit:line.debit||0,Credit:line.credit||0,Source:entry.source,'Source ID':entry.sourceId||''})));
  const chartRows=accounts.map(account=>({'Account Number':account.id,'Account Name':account.name,Type:account.type,'Normal Balance':account.normalBalance,Active:account.active!==false?'Yes':'No'})); const trialRows=trial.rows.map(row=>({Account:row.name,Type:row.type,Debits:row.debit,Credits:row.credit,Balance:row.balance})); const balanceRows=[{Section:'Assets',Amount:sheet.assets},{Section:'Liabilities',Amount:sheet.liabilities},{Section:'Posted equity',Amount:sheet.equityPosted},{Section:'Retained earnings and current income',Amount:sheet.retainedEarningsAndCurrentIncome},{Section:'Total equity',Amount:sheet.equity},{Section:'Difference',Amount:sheet.difference}]; const pnlRows=[{Section:'Revenue',Amount:pnl.revenue},{Section:'Expenses',Amount:pnl.expenses},{Section:'Net income',Amount:pnl.netIncome}]; const priorDate=new Date(`${yearStart}T00:00:00Z`); priorDate.setUTCDate(priorDate.getUTCDate()-1); const beginningTrial=trialBalance(system.ledger,companyId,priorDate.toISOString().slice(0,10)); const cashAccounts=accounts.filter(account=>account.cashFlowRole==='cash'||(account.type==='asset'&&/(cash|bank|checking|savings|operating|chase)/i.test(account.name))); const cashRows=cashAccounts.map(account=>{const beginning=beginningTrial.rows.find(row=>row.accountId===account.id)?.balance||0;const ending=trial.rows.find(row=>row.accountId===account.id)?.balance||0;return {Account:account.name,'Beginning cash':beginning,'Ending cash':ending,'Net change':amount(ending-beginning)}}); cashRows.push({Account:'TOTAL CASH','Beginning cash':amount(cashRows.reduce((sum,row)=>sum+row['Beginning cash'],0)),'Ending cash':amount(cashRows.reduce((sum,row)=>sum+row['Ending cash'],0)),'Net change':amount(cashRows.reduce((sum,row)=>sum+row['Net change'],0))});
  const bankRows=(company.bankTransactions||[]).filter(item=>item.postedDate<=throughDate).map(item=>({Account:accountName(item.accountId),Date:item.postedDate,Description:item.description,Amount:item.amount,Status:item.status,'Matched Expense':item.match?.expenseId||''})); const reconciliationRows=(company.reconciliations||[]).filter(item=>item.endDate<=throughDate).map(item=>({Account:accountName(item.accountId),'Start Date':item.startDate,'End Date':item.endDate,'Statement Ending':item.statementEndingBalance,'Book Ending':item.bookEndingBalance,Difference:amount(item.statementEndingBalance-item.bookEndingBalance),Status:item.status,'Snapshot Hash':item.snapshotHash})); const payableRows=readiness.summary.accountsPayable.bills.map(row=>({Vendor:row.vendor,'Vendor ID':row.qboVendorId||'','Bill Date':row.transactionDate,'Due Date':row.dueDate,Reference:row.reference,Age:row.bucket,Amount:row.total,Status:row.status})); const taxRows=readiness.summary.salesTax.states.map(row=>({State:row.state,'Taxable Sales':row.taxableSales,'Exempt Sales':row.exemptSales,'Tax Collected':row.taxCollected,'Tax Remitted':row.taxRemitted,Liability:row.liability})); const contractorRows=readiness.summary.contractors.contractors.map(row=>({'Vendor ID':row.vendorId,'Vendor Name':row.vendorName,'Tax ID Last 4':row.taxIdLast4||'','W-9 On File':row.w9OnFile?'Yes':'No',Total:row.total,Reportable:row.reportable?'Yes':'No',Blockers:row.blockers.join('; ')}));
  const exceptionRows=(system.automation?.alerts||[]).map(item=>({Type:item.type,Severity:item.severity,Title:item.title,Status:item.status,'First Seen':item.firstSeenAt,'Resolved At':item.resolvedAt||'',Entity:item.entityId||''})); const auditRows=(system.ledger.audit||[]).filter(item=>!item.companyId||item.companyId===companyId).map(item=>({Time:item.at,Action:item.action,Actor:item.actorId||'',Entity:item.entityType||'','Entity ID':item.entityId||'','Previous Hash':item.previousHash||'',Hash:item.hash})); const evidenceRows=evidenceDocuments.map(item=>({'Document ID':item.id,'File Name':item.file_name||item.fileName,Type:item.document_type||item.documentType,Status:item.status,SHA256:item.sha256,'Created At':item.created_at||item.createdAt}));
  const fileSpecs=[
    ['chart-of-accounts.csv',csv(['Account Number','Account Name','Type','Normal Balance','Active'],chartRows)],['journal-entries-qbo.csv',csv(['Journal No.','Journal Date','Account Name','Description','Debits','Credits','Name','Class','Location'],journalRows)],['general-ledger.csv',csv(['Date','Journal ID','Account','Description','Debit','Credit','Source','Source ID'],ledgerRows)],['trial-balance.csv',csv(['Account','Type','Debits','Credits','Balance'],trialRows)],['balance-sheet.csv',csv(['Section','Amount'],balanceRows)],['profit-and-loss.csv',csv(['Section','Amount'],pnlRows)],['cash-flow-workpaper.csv',csv(['Account','Beginning cash','Ending cash','Net change'],cashRows)],['accounts-payable-aging.csv',csv(['Vendor','Vendor ID','Bill Date','Due Date','Reference','Age','Amount','Status'],payableRows)],['bank-registers.csv',csv(['Account','Date','Description','Amount','Status','Matched Expense'],bankRows)],['reconciliations.csv',csv(['Account','Start Date','End Date','Statement Ending','Book Ending','Difference','Status','Snapshot Hash'],reconciliationRows)],['sales-tax-liability.csv',csv(['State','Taxable Sales','Exempt Sales','Tax Collected','Tax Remitted','Liability'],taxRows)],['contractor-summary.csv',csv(['Vendor ID','Vendor Name','Tax ID Last 4','W-9 On File','Total','Reportable','Blockers'],contractorRows)],['fixed-assets.csv',csv(['id','description','acquiredDate','cost','accountId','status'],system.fixedAssets||[])],['loans.csv',csv(['id','lender','accountId','principalBalance','statementDate','status'],system.loans||[])],['exceptions.csv',csv(['Type','Severity','Title','Status','First Seen','Resolved At','Entity'],exceptionRows)],['audit-log.csv',csv(['Time','Action','Actor','Entity','Entity ID','Previous Hash','Hash'],auditRows)],['evidence-index.csv',csv(['Document ID','File Name','Type','Status','SHA256','Created At'],evidenceRows)],['close-readiness.json',JSON.stringify(readiness,null,2)],['README.txt',`HiveLogic accountant close package\r\nCompany: ${company.name}\r\nThrough date: ${throughDate}\r\nBasis: ${basis}\r\n\r\nUse close-review.xlsx for review, journal-entries-qbo.csv for QuickBooks Online journal import, and the CSV workpapers for other accounting systems. manifest.json contains SHA-256 checksums for every generated file. Original evidence is included under evidence/.`]
  ].map(([name,content])=>({name,content:Buffer.from(content)}));
  fileSpecs.push({name:'close-review.xlsx',content:createXlsx([{name:'Close Summary',rows:[['Company',company.name],['Through date',throughDate],['Basis',basis],['Readiness score',readiness.score],['Status','READY'],[],['Check','Result','Detail'],...readiness.checks.map(item=>[item.label,item.passed?'PASS':'FAIL',item.detail])]},{name:'Trial Balance',rows:rowsForWorkbook(['Account','Type','Debits','Credits','Balance'],trialRows)},{name:'Profit and Loss',rows:rowsForWorkbook(['Section','Amount'],pnlRows)},{name:'Balance Sheet',rows:rowsForWorkbook(['Section','Amount'],balanceRows)},{name:'Cash Flow',rows:rowsForWorkbook(['Account','Beginning cash','Ending cash','Net change'],cashRows)},{name:'Bills Owed',rows:rowsForWorkbook(['Vendor','Vendor ID','Bill Date','Due Date','Reference','Age','Amount','Status'],payableRows)},{name:'Journal Entries',rows:rowsForWorkbook(['Journal No.','Journal Date','Account Name','Description','Debits','Credits','Name','Class','Location'],journalRows)},{name:'Reconciliations',rows:rowsForWorkbook(['Account','Start Date','End Date','Statement Ending','Book Ending','Difference','Status','Snapshot Hash'],reconciliationRows)},{name:'Exceptions',rows:rowsForWorkbook(['Type','Severity','Title','Status','First Seen','Resolved At','Entity'],exceptionRows)}])});
  fileSpecs.push({name:'reconciliation-summary.pdf',content:createSimplePdf(`${company.name} reconciliation summary through ${throughDate}`,[`Readiness: ${readiness.score}%`,...reconciliationRows.map(row=>`${row.Account}: ${row['Start Date']} to ${row['End Date']}, statement ${row['Statement Ending']}, books ${row['Book Ending']}, difference ${row.Difference}, ${row.Status}`)])});
  for(const document of evidenceDocuments){const storagePath=document.storage_path||document.storagePath;if(storagePath&&existsSync(storagePath)){const safe=path.basename(document.file_name||document.fileName).replace(/[^a-zA-Z0-9._-]/g,'_');fileSpecs.push({name:`evidence/${document.id}-${safe}`,content:readFileSync(storagePath)});}}
  const manifest={format:'hivelogic-accountant-close-v1',companyId,companyName:company.name,throughDate,basis,generatedAt:new Date().toISOString(),readinessScore:readiness.score,auditHead:verifyAuditChain(system.ledger).head,files:fileSpecs.map(file=>({name:file.name,bytes:file.content.length,sha256:checksum(file.content)}))}; fileSpecs.push({name:'manifest.json',content:Buffer.from(JSON.stringify(manifest,null,2))}); const buffer=createZip(fileSpecs); return {buffer,sha256:checksum(buffer),manifest,readiness,files:fileSpecs.map(file=>({name:file.name,bytes:file.content.length,sha256:checksum(file.content)}))};
}
