import test from 'node:test'; import assert from 'node:assert/strict';
import { createLedger, addCompany, createEntry, approveEntry, postEntry, setPeriodLock, correctEntry, balanceSheet, verifyAuditChain } from '../src/ledger.js';
import { createControlStore, requestApproval, decideApproval, enqueueQboSync, beginQboSync, finishQboSync } from '../src/controls.js';
import { importBankFeed, confirmBankMatch, reconcileStatement, verifyReconciliation } from '../src/banking.js';
import { incomeStatement, salesTaxLiability, contractorTaxReport } from '../src/reporting.js'; import { buildExportPackage, verifyExportPackage } from '../src/exports.js';

test('end-to-end accounting acceptance: expense to bank, books, QBO, close, tax, contractor, correction, and export',()=>{
  const controller={id:'controller',role:'controller'},submitter={id:'submitter',role:'submitter'},approver={id:'approver',role:'approver'},bookkeeper={id:'bookkeeper',role:'bookkeeper'};
  const ledger=createLedger();addCompany(ledger,{id:'co',name:'GH Group',basis:'accrual',accounts:[{id:'bank',name:'Bank',type:'asset'},{id:'card',name:'Credit Card',type:'liability'},{id:'expense',name:'Materials',type:'expense'},{id:'revenue',name:'Revenue',type:'income'},{id:'tax',name:'Sales Tax Payable',type:'liability'},{id:'equity',name:'Retained Earnings',type:'equity'}]},controller);
  const expense={id:'e1',vendor:'ABC Supply',transactionDate:'2026-07-19',total:106.35};
  const journal=createEntry(ledger,{companyId:'co',date:expense.transactionDate,description:'ABC Supply materials',source:'expense',sourceId:expense.id,lines:[{accountId:'expense',debit:106.35},{accountId:'card',credit:106.35}]},submitter);approveEntry(ledger,'co',journal.id,approver);postEntry(ledger,'co',journal.id,controller,'expense:e1');
  const qboPayload={EntityRef:{value:'22412',type:'Vendor'},Line:[{Amount:106.35}]};const controls=createControlStore();const approval=requestApproval(controls,{companyId:'co',entityType:'expense',entityId:expense.id,payload:qboPayload},submitter);decideApproval(controls,approval.id,'approve','Receipt verified',approver);const outbox=enqueueQboSync(controls,{companyId:'co',entityType:'expense',entityId:expense.id,payload:qboPayload,approvalRequestId:approval.id});beginQboSync(controls,outbox.id,bookkeeper);finishQboSync(controls,outbox.id,{ok:true,qboId:'qbo-123'},bookkeeper);assert.equal(outbox.status,'complete');
  const bank=importBankFeed(ledger,'co',[{accountId:'card',externalId:'b1',postedDate:'2026-07-20',amount:-106.35,description:'ABC SUPPLY'}],'feed:jul').transactions[0];confirmBankMatch(ledger,'co',bank.id,expense,bookkeeper);const rec=reconcileStatement(ledger,'co',{accountId:'card',startDate:'2026-07-01',endDate:'2026-07-31',statementBeginningBalance:0,statementEndingBalance:106.35,bookEndingBalance:106.35},bookkeeper);assert.equal(verifyReconciliation(ledger,'co',rec.id).valid,true);
  assert.equal(incomeStatement(ledger,'co',{startDate:'2026-01-01',endDate:'2026-12-31'}).expenses,106.35);assert.equal(balanceSheet(ledger,'co','2026-12-31').balanced,true);setPeriodLock(ledger,'co','2026-07',true,controller);assert.throws(()=>createEntry(ledger,{companyId:'co',date:'2026-07-31',description:'Late',lines:[{accountId:'expense',debit:1},{accountId:'card',credit:1}]},controller),/locked/);
  assert.equal(salesTaxLiability([{date:'2026-07-01',taxState:'CT',taxableAmount:100,taxCollected:6.35}],[], '2026-12-31').totalLiability,6.35);assert.equal(contractorTaxReport([{id:'sub',name:'Sub',track1099:true,w9OnFile:true,taxIdLast4:'1234'}],[{vendorId:'sub',date:'2026-06-01',amount:800}],{year:2026,threshold:600}).reportableCount,1);
  setPeriodLock(ledger,'co','2026-07',false,controller);const correction=correctEntry(ledger,'co',journal.id,{date:'2026-08-01',description:'Corrected materials',lines:[{accountId:'expense',debit:100},{accountId:'card',credit:100}]},'Vendor refunded 6.35',controller);assert.equal(correction.original.status,'posted');assert.equal(verifyAuditChain(ledger).valid,true);
  const pkg=buildExportPackage({ledger,companyId:'co',audience:'accountant',throughDate:'2026-12-31',fiscalYearStartDate:'2026-01-01',vendors:[],contractorPayments:[]});assert.equal(verifyExportPackage(pkg).valid,true);
});
