import test from 'node:test'; import assert from 'node:assert/strict';
import { createLedger, addCompany, createEntry, postEntry, reverseEntry } from '../src/ledger.js';
import { basisTrialBalance, basisBalanceSheet, incomeStatement, generalLedgerReport, retainedEarnings, salesTaxLiability, contractorTaxReport, accountsPayableAging, accountsReceivableAging, expenseSummary } from '../src/reporting.js';
const controller={id:'c',role:'controller'}; const accounts=[{id:'cash',name:'Cash',type:'asset'},{id:'ar',name:'A/R',type:'asset'},{id:'equity',name:'Equity',type:'equity'},{id:'revenue',name:'Revenue',type:'income'},{id:'expense',name:'Expense',type:'expense'}];
function setup(){const ledger=createLedger();addCompany(ledger,{id:'co',name:'GH',accounts},controller);return ledger} function post(ledger,input,key){const entry=createEntry(ledger,{companyId:'co',...input},controller);entry.status='approved';postEntry(ledger,'co',entry.id,controller,key);return entry}

test('cash and accrual statements use basis-specific balanced lines and recognition dates',()=>{const ledger=setup();post(ledger,{date:'2026-01-10',cashDate:'2026-02-05',description:'Invoice',lines:[{accountId:'ar',debit:1000},{accountId:'revenue',credit:1000}],cashLines:[{accountId:'cash',debit:1000},{accountId:'revenue',credit:1000}]},'inv:1');assert.equal(incomeStatement(ledger,'co',{startDate:'2026-01-01',endDate:'2026-01-31',basis:'accrual'}).revenue,1000);assert.equal(incomeStatement(ledger,'co',{startDate:'2026-01-01',endDate:'2026-01-31',basis:'cash'}).revenue,0);assert.equal(incomeStatement(ledger,'co',{startDate:'2026-02-01',endDate:'2026-02-28',basis:'cash'}).revenue,1000);const cashTrial=basisTrialBalance(ledger,'co',{throughDate:'2026-02-28',basis:'cash'});assert.equal(cashTrial.rows.find(row=>row.accountId==='cash').balance,1000);assert.equal(cashTrial.rows.find(row=>row.accountId==='ar').balance,0);assert.equal(cashTrial.balanced,true);assert.equal(basisBalanceSheet(ledger,'co',{throughDate:'2026-02-28',basis:'cash'}).balanced,true)});
test('general ledger report exposes balanced account-level drilldown for the selected basis',()=>{const ledger=setup();post(ledger,{date:'2026-01-10',cashDate:'2026-02-05',description:'Invoice',source:'invoice',sourceId:'i1',lines:[{accountId:'ar',debit:1000},{accountId:'revenue',credit:1000}],cashLines:[{accountId:'cash',debit:1000},{accountId:'revenue',credit:1000}]},'inv:ledger');const accrual=generalLedgerReport(ledger,'co',{startDate:'2026-01-01',throughDate:'2026-01-31',basis:'accrual'});assert.equal(accrual.rows.length,2);assert.equal(accrual.rows[0].accountName,'A/R');assert.equal(accrual.totalDebits,1000);assert.equal(accrual.totalCredits,1000);assert.equal(accrual.balanced,true);const cash=generalLedgerReport(ledger,'co',{startDate:'2026-02-01',throughDate:'2026-02-28',basis:'cash'});assert.equal(cash.rows.find(row=>row.accountId==='cash').debit,1000)});
test('reversals preserve and cancel both accrual and cash-basis journal views',()=>{const ledger=setup();const entry=post(ledger,{date:'2026-01-10',cashDate:'2026-02-05',description:'Invoice',lines:[{accountId:'ar',debit:1000},{accountId:'revenue',credit:1000}],cashLines:[{accountId:'cash',debit:1000},{accountId:'revenue',credit:1000}]},'inv:reverse');reverseEntry(ledger,'co',entry.id,'2026-03-01','Invoice voided',controller);assert.equal(basisTrialBalance(ledger,'co',{throughDate:'2026-12-31',basis:'accrual'}).rows.find(row=>row.accountId==='ar').balance,0);assert.equal(basisTrialBalance(ledger,'co',{throughDate:'2026-12-31',basis:'cash'}).rows.find(row=>row.accountId==='cash').balance,0)});
test('retained earnings separates prior and current-year income',()=>{const ledger=setup();post(ledger,{date:'2025-12-20',cashDate:'2025-12-20',description:'Prior sale',lines:[{accountId:'cash',debit:100},{accountId:'revenue',credit:100}]},'sale:old');post(ledger,{date:'2026-02-01',cashDate:'2026-02-01',description:'Current sale',lines:[{accountId:'cash',debit:50},{accountId:'revenue',credit:50}]},'sale:new');const result=retainedEarnings(ledger,'co','2026-01-01','2026-12-31');assert.equal(result.priorRetainedEarnings,100);assert.equal(result.currentIncome,50)});
test('sales-tax liabilities are separate from vendor receipt tax and net remittances by state',()=>{const result=salesTaxLiability([{date:'2026-07-01',taxState:'CT',taxableAmount:1000,taxCollected:63.5},{date:'2026-07-02',taxState:'NY',taxableAmount:500,taxCollected:43.75}],[{date:'2026-07-15',taxState:'CT',amount:20}]);assert.equal(result.states.find(row=>row.state==='CT').liability,43.5);assert.equal(result.totalLiability,87.25)});
test('contractor reporting is threshold-configurable and flags missing W-9 data',()=>{const result=contractorTaxReport([{id:'v1',name:'Sub One',track1099:true,w9OnFile:false},{id:'v2',name:'Sub Two',track1099:true,w9OnFile:true,taxIdLast4:'1234'}],[{vendorId:'v1',date:'2026-03-01',amount:700},{vendorId:'v2',date:'2026-04-01',amount:500}],{year:2026,threshold:600});assert.equal(result.reportableCount,1);assert.match(result.blockers[0].blocker,/W-9/)});
test('accounts payable aging includes only posted open bills and assigns overdue buckets',()=>{const result=accountsPayableAging([{id:'b1',transactionKind:'bill',vendor:'Supply Co',transactionDate:'2026-05-01',dueDate:'2026-06-30',total:200,status:'approved_for_qbo'},{id:'b2',transactionKind:'bill',vendor:'Paid Co',transactionDate:'2026-05-01',dueDate:'2026-05-31',total:50,status:'paid'},{id:'b3',transactionKind:'bill',vendor:'Draft Co',transactionDate:'2026-06-01',dueDate:'2026-07-15',total:75,status:'ready_for_review'}],{throughDate:'2026-07-20',postedExpenseIds:['b1']});assert.equal(result.count,1);assert.equal(result.totalOutstanding,200);assert.equal(result.bills[0].bucket,'1–30 days');assert.equal(result.buckets['1–30 days'],200)});

test('accounts receivable aging excludes drafts and paid invoices, buckets by due date, and reports undated invoices separately', () => { const result = accountsReceivableAging([{ id: 'i1', invoiceNumber: '1001', total: 500, balance: 500, dueDate: '2026-06-01', status: 'past_due' }, { id: 'i2', invoiceNumber: '1002', total: 300, balance: 0, dueDate: '2026-06-01', status: 'paid' }, { id: 'i3', invoiceNumber: '1003', total: 200, balance: 200, dueDate: '2026-07-10', status: 'draft' }, { id: 'i4', invoiceNumber: '1004', total: 150, balance: 150, dueDate: null, issuedDate: null, status: 'sent' }], { throughDate: '2026-07-20' }); assert.equal(result.count, 1); assert.equal(result.totalOutstanding, 500); assert.equal(result.undatedExcluded, 1); assert.equal(result.invoices[0].bucket, '31–60 days'); assert.equal(result.buckets['31–60 days'], 500); });
test('expense summary groups real submitted allocations by vendor or by expense home, excluding drafts and rejections', () => { const expenses = [{ status: 'submitted_for_review', vendor: 'ABC Supply', transactionDate: '2026-06-05', allocations: [{ amount: 120, ownerType: 'job' }, { amount: 30, ownerType: 'overhead' }] }, { status: 'draft_saved', vendor: 'ABC Supply', transactionDate: '2026-06-06', allocations: [{ amount: 999, ownerType: 'job' }] }, { status: 'rejected', vendor: 'Bad Co', transactionDate: '2026-06-07', allocations: [{ amount: 999, ownerType: 'job' }] }, { status: 'approved_for_qbo', vendor: 'Truck Depot', transactionDate: '2026-06-08', allocations: [{ amount: 75, ownerType: 'truck' }] }]; const byVendor = expenseSummary(expenses, { startDate: '2026-06-01', endDate: '2026-06-30', groupBy: 'vendor' }); assert.equal(byVendor.grandTotal, 225); assert.equal(byVendor.rows.find(r => r.key === 'ABC Supply').total, 150); assert.equal(byVendor.transactionCount, 2); const byHome = expenseSummary(expenses, { startDate: '2026-06-01', endDate: '2026-06-30', groupBy: 'ownerType' }); assert.equal(byHome.rows.find(r => r.key === 'job').total, 120); assert.equal(byHome.rows.find(r => r.key === 'overhead').total, 30); assert.equal(byHome.rows.find(r => r.key === 'truck').total, 75); });
