-- 006_visual_intel.sql
-- ADDITIVE ONLY. Creates the Visual Intelligence tables (photo/video capture,
-- tags, annotations, timeline, comments) for api/visual-intel.js.
-- Does not alter jobs/clients/invoices/quotes/requests/visits/expenses/
-- time_sheet_entries/users/integrations/documents/client_locations/
-- office_location/workforce_time_sessions or any other existing table.
--
-- Run this once in the Supabase SQL editor (Project -> SQL Editor -> New
-- query -> paste -> Run) before hitting /api/visual-intel for the first
-- time. Safe to run more than once (IF NOT EXISTS guards).
--
-- All rows key to a real job by jobs.jobber_id (text) -- there is no local
-- "job" concept here, this is additive documentation attached to real jobs.

create table if not exists media (
  id uuid primary key default gen_random_uuid(),
  job_id text not null,                 -- references jobs.jobber_id (not a FK: jobs is a synced/read-only table)
  media_type text not null check (media_type in ('PHOTO', 'VIDEO')),
  storage_path text not null,           -- path inside the 'media' Storage bucket, same pattern as documents.storage_path
  mime_type text,
  size_bytes bigint,
  thumbnail_path text,                  -- populated for video (frame grab); null for photos (client renders the original)
  captured_at timestamptz not null default now(),
  gps_lat numeric,
  gps_lng numeric,
  rotation smallint not null default 0 check (rotation in (0, 90, 180, 270)),
  offline_client_id text,               -- de-dupe key for offline-captured uploads that retry
  uploaded_by uuid,                     -- references auth.users.id (Supabase Auth), nullable if attribution unknown
  created_at timestamptz not null default now()
);
create index if not exists media_job_id_idx on media (job_id);
create index if not exists media_captured_at_idx on media (captured_at desc);
create unique index if not exists media_offline_client_id_idx on media (offline_client_id) where offline_client_id is not null;

create table if not exists media_analysis (
  id uuid primary key default gen_random_uuid(),
  media_id uuid not null references media (id) on delete cascade,
  description text,
  room text,
  trade text,
  materials text[],
  damage text,
  safety_issue text,
  confidence numeric,                   -- 0..1, real model confidence -- never fabricated (Law 1). Null until a real analysis has run.
  model text,                           -- e.g. 'claude-sonnet-4-5', so we always know what produced this row
  analyzed_at timestamptz
);
create unique index if not exists media_analysis_media_id_idx on media_analysis (media_id);

create table if not exists tags (
  id uuid primary key default gen_random_uuid(),
  job_id text not null,
  name text not null,
  source text not null default 'MANUAL' check (source in ('MANUAL', 'AI')),
  created_at timestamptz not null default now()
);
create index if not exists tags_job_id_idx on tags (job_id);
create unique index if not exists tags_job_id_name_idx on tags (job_id, lower(name));

create table if not exists media_tags (
  media_id uuid not null references media (id) on delete cascade,
  tag_id uuid not null references tags (id) on delete cascade,
  primary key (media_id, tag_id)
);

create table if not exists annotations (
  id uuid primary key default gen_random_uuid(),
  media_id uuid not null references media (id) on delete cascade,
  annotation_type text not null check (annotation_type in ('DRAWING', 'ARROW', 'LINE', 'RECTANGLE', 'CIRCLE', 'TEXT', 'MEASUREMENT', 'BLUR')),
  data jsonb not null,                  -- {points, color, strokeWidth, text} -- same shape the old companycam-killer prototype used
  frame_time_ms integer,                -- for video annotations pinned to a timeline position; null for photos
  created_by uuid,
  created_at timestamptz not null default now(),
  superseded_by uuid references annotations (id) -- edits create a new row and point the old one here; never mutate in place
);
create index if not exists annotations_media_id_idx on annotations (media_id);

create table if not exists timeline_events (
  id uuid primary key default gen_random_uuid(),
  job_id text not null,
  label text not null,
  source text not null default 'AUTO' check (source in ('AUTO', 'MANUAL')),
  media_id uuid references media (id) on delete set null, -- set when an AUTO event was generated by a specific upload
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists timeline_events_job_id_idx on timeline_events (job_id);
create index if not exists timeline_events_occurred_at_idx on timeline_events (occurred_at desc);

create table if not exists media_comments (
  id uuid primary key default gen_random_uuid(),
  media_id uuid not null references media (id) on delete cascade,
  body text not null,
  created_by uuid,
  created_at timestamptz not null default now()
);
create index if not exists media_comments_media_id_idx on media_comments (media_id);

-- Polymorphic link so a photo/video can attach to any other HiveLogic entity
-- (an invoice, a quote, a change order, etc.) without a schema change per
-- new entity type -- same pattern the original companycam-killer prototype
-- used, kept here since HiveLogic already has several distinct entity
-- tables (jobs, invoices, quotes, requests, visits, expenses) media may
-- need to reference beyond just its owning job.
create table if not exists media_entity_links (
  id uuid primary key default gen_random_uuid(),
  media_id uuid not null references media (id) on delete cascade,
  entity_type text not null check (entity_type in ('JOB', 'INVOICE', 'QUOTE', 'REQUEST', 'VISIT', 'EXPENSE', 'TIMESHEET', 'CLIENT')),
  entity_id text not null,              -- the external jobber_id (or equivalent) of the linked entity
  created_at timestamptz not null default now()
);
create index if not exists media_entity_links_media_id_idx on media_entity_links (media_id);
create index if not exists media_entity_links_entity_idx on media_entity_links (entity_type, entity_id);

-- Storage bucket: run this via the Supabase dashboard (Storage -> New bucket)
-- rather than SQL -- name it 'media', mark it private (like 'docs'), and
-- copy the 'docs' bucket's RLS policies so authenticated HiveLogic users can
-- upload/read their tenant's photos the same way Documents already works.
