// api/ads.js - Vercel serverless function
// Paid ads & social platform foundation (Meta, Google Ads, TikTok).
// Step 1 of the paid-ads-social build: the connection framework. Mirrors
// the Phase 15 Universal Connections flow in api/marketing.js exactly (see
// api/_lib/connection-states.js), applied to the new ad_platform_connections
// table (sql/058) instead of marketing_platform_connections -- ad
// platforms need their own row shape (business_account_id, ad_account_id,
// env_var_name) but the same connect -> verify-reporting -> verify-draft
// -> enable-launch sequence and issue-state vocabulary.
//
// Usage:
//   GET  /api/ads?resource=ad_connections
//     -> current state of all 3 ad platforms, real rows from
//        ad_platform_connections (not_connected if no row exists yet).
//   POST /api/ads?resource=ad_connection_transition
//     body: { platform, toState, note?, envVarName? }
//     -> moves one platform's connection to a new state, enforcing the
//        same legal-transition rules as marketing_platform_connections.
//
//   GET  /api/ads?resource=ad_campaigns[&platform=][&status=]
//     -> real ad_campaigns rows, optionally filtered.
//   POST /api/ads?resource=ad_campaign_draft
//     body: { platform, objective, division, dailyBudgetCents, adCopy? }
//     -> creates a draft ad_campaigns row. adCopy is optional -- if
//        omitted, ad copy is generated by AI, grounded only in real
//        division job facts + service territory facts (never fabricated),
//        and refuses honestly (409) if ANTHROPIC_API_KEY is not set.
//   POST /api/ads?resource=ad_campaign_review
//     body: { campaignId, decision: 'approve'|'reject', reason? }
//     -> approve moves draft -> pending_review, but only after a real
//        budget-headroom check (api/_lib/ad-budget-governor.js) passes;
//        reject moves draft -> rejected with a stored reason. Neither
//        touches a real platform -- that is still step 3.
//
//   POST /api/ads?resource=ad_campaign_launch
//     body: { campaignId, linkUrl? }
//     -> the first real platform action in this build: launches an
//        approved (pending_review) campaign for real. Meta goes through
//        the Graph API (api/_lib/ad-platform-meta.js); Google Ads goes
//        through the Google Ads REST API (api/_lib/ad-platform-google.js).
//        Requires that platform's connection to already be launch_enabled
//        and its real credentials to be present as Vercel project
//        settings, and re-checks budget headroom before calling out. On
//        success moves the campaign to active with its real
//        external_campaign_id; on failure records the classified
//        connection issue state (needs_reauth/policy_blocked/
//        billing_blocked/needs_attention) and leaves the campaign in
//        pending_review for a retry once fixed.
//
//   POST /api/ads?resource=ad_campaign_pause
//     body: { campaignId, reason? }
//     -- pauses a real, currently active Meta or Google Ads campaign. Only
//        an active campaign can be paused. A failure is classified and
//        recorded on the connection exactly like a launch failure -- never
//        swallowed.
//
//   POST /api/ads?resource=ad_spend_sync
//     body: { campaignId, date? }  (date defaults to today, UTC, YYYY-MM-DD)
//     -- pulls that day's real reported spend for a launched Meta or
//        Google Ads campaign from that platform's own reporting endpoint
//        and upserts it into ad_spend_ledger (the same table the budget
//        governor sums against the cap). Never estimates or invents a
//        number -- only ever writes what the platform itself reports.
//
// Meta, Google Ads, and TikTok are all wired up for a real
// launch/pause/spend-sync now (steps 3 + 5, all three ad platforms this
// build was scoped for). None of the three launch codepaths have ever been
// exercised against a real ad account -- see the header of each
// api/_lib/ad-platform-*.js file. Organic social posting (step 6) is a
// separate subsystem in api/social-posts.js, not this file.
//
// Google Ads credential shape: ad_platform_connections.env_var_name for
// platform='google_ads' must point to a Vercel env var whose value is a
// JSON blob {"developerToken":"...","clientId":"...","clientSecret":"...",
// "refreshToken":"..."} -- see the header of api/_lib/ad-platform-google.js
// for why (Google Ads needs four secrets, not one token like Meta).
// ad_platform_connections.ad_account_id is the Google Ads Customer ID;
// business_account_id is the optional MCC (manager account) id.
//
// TikTok credential shape matches Meta's -- a single long-lived access
// token in the named env var, ad_account_id reused as the TikTok Advertiser
// ID. See the header of api/_lib/ad-platform-tiktok.js for TikTok's honest
// limitation: real ads require a real uploaded video/image asset id, which
// this build has no upload pipeline for yet -- launch refuses rather than
// fabricating creative when ad_copy has no mediaAssetId.

import { supabaseRequest as defaultSupabaseRequest } from './_lib/jobber.js';
import { requireUser } from './_lib/require-user.js';
import {
  CONNECTION_STATES,
  ISSUE_STATES,
  isValidConnectionTransition,
} from './_lib/connection-states.js';
import { checkBudgetHeadroom } from './_lib/ad-budget-governor.js';
import { realDivisionJobFacts, realServiceTerritoryFacts, KNOWN_DIVISIONS } from './_lib/ad-copy-grounding.js';
import { generateAdCopy, isAdCopyGenerationConfigured } from './_lib/ad-copy-generator.js';
import { launchMetaCampaign as defaultLaunchMetaCampaign, pauseMetaCampaign as defaultPauseMetaCampaign, syncMetaCampaignSpend as defaultSyncMetaCampaignSpend } from './_lib/ad-platform-meta.js';
import { launchGoogleAdsCampaign as defaultLaunchGoogleAdsCampaign, pauseGoogleAdsCampaign as defaultPauseGoogleAdsCampaign, syncGoogleAdsCampaignSpend as defaultSyncGoogleAdsCampaignSpend } from './_lib/ad-platform-google.js';
import { launchTikTokCampaign as defaultLaunchTikTokCampaign, pauseTikTokCampaign as defaultPauseTikTokCampaign, syncTikTokCampaignSpend as defaultSyncTikTokCampaignSpend } from './_lib/ad-platform-tiktok.js';

const AD_PLATFORMS = new Set(['meta', 'google_ads', 'tiktok']);

// Platforms with a real, live launch/pause/spend-sync integration wired up
// in this file. Checked in one place so a future platform means adding it
// here plus its adapter import, not re-auditing every handler. As of this
// build every member of AD_PLATFORMS is also live -- kept as a distinct set
// (rather than reusing AD_PLATFORMS directly) so the two concepts stay
// decoupled if a fourth platform is ever added to AD_PLATFORMS before its
// adapter is built.
const LIVE_PLATFORMS = new Set(['meta', 'google_ads', 'tiktok']);

// Builds a real, always-current "X, Y, and Z" list of live platform labels
// for user-facing error strings, rather than hand-maintaining the sentence
// in three separate places every time a platform goes live.
function livePlatformLabelsText() {
  const labels = [...LIVE_PLATFORMS].map((p) => AD_PLATFORM_LABELS[p]);
  if (labels.length === 1) return labels[0];
  return labels.slice(0, -1).join(', ') + ', and ' + labels[labels.length - 1];
}

const AD_PLATFORM_LABELS = {
  meta: 'Meta (Facebook + Instagram)',
  google_ads: 'Google Ads',
  tiktok: 'TikTok Ads',
};

const AD_OBJECTIVES = new Set(['lead_gen', 'traffic', 'awareness', 'conversions']);

// Real per-platform credential resolution. Meta's single access token lives
// directly in the named env var; Google Ads' four secrets live together as
// one JSON blob in the named env var (see file header for why). Returns
// null (never a fabricated/partial value) if anything required is missing.
//
// opts.forLaunch matters only for Meta: a launch needs the ad account and
// page to create new objects in, but pause/spend-sync only ever act on an
// object that already has a real external_campaign_id, so the access token
// alone is enough -- exactly the distinction the original Meta-only code
// drew (launch checked ad_account_id/page_id; pause and spend-sync did
// not). Google Ads always needs its Customer ID in the URL path for every
// call, so that check applies regardless of forLaunch.
function resolvePlatformConn(platform, connection, opts = {}) {
  if (!connection || !connection.env_var_name) return null;
  const raw = process.env[connection.env_var_name];
  if (!raw) return null;

  if (platform === 'meta') {
    if (opts.forLaunch && (!connection.ad_account_id || !connection.page_id)) return null;
    return { accessToken: raw, adAccountId: connection.ad_account_id, pageId: connection.page_id };
  }

  if (platform === 'google_ads') {
    if (!connection.ad_account_id) return null;
    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch (e) {
      return null;
    }
    if (!parsed || !parsed.developerToken || !parsed.clientId || !parsed.clientSecret || !parsed.refreshToken) return null;
    return {
      developerToken: parsed.developerToken,
      clientId: parsed.clientId,
      clientSecret: parsed.clientSecret,
      refreshToken: parsed.refreshToken,
      customerId: connection.ad_account_id,
      loginCustomerId: connection.business_account_id || null,
    };
  }

  if (platform === 'tiktok') {
    // Credential shape matches Meta's: env_var_name holds the raw access
    // token, ad_account_id is reused as the TikTok Advertiser ID.
    // identityId (a real TikTok Identity id, required to attribute ad
    // creative) reuses the page_id column -- same "platform-specific
    // secondary id used for ad creative attribution" role page_id plays for
    // Meta, rather than adding a new migration column for one field.
    if (!connection.ad_account_id) return null;
    if (opts.forLaunch && !connection.page_id) return null;
    return { accessToken: raw, advertiserId: connection.ad_account_id, identityId: connection.page_id || null };
  }

  return null;
}

export async function adConnectionsShape(tenantId = 'ghgrp', supabaseRequest = defaultSupabaseRequest) {
  const res = await supabaseRequest(`ad_platform_connections?tenant_id=eq.${encodeURIComponent(tenantId)}&select=*`);
  if (!res.ok) throw new Error(`Failed to read ad_platform_connections: ${await res.text()}`);
  const rows = await res.json();
  const byPlatform = new Map(rows.map((r) => [r.platform, r]));
  return [...AD_PLATFORMS].map((platform) => {
    const row = byPlatform.get(platform);
    return {
      platform,
      label: AD_PLATFORM_LABELS[platform],
      state: row ? row.state : 'not_connected',
      businessAccountId: row ? row.business_account_id : null,
      adAccountId: row ? row.ad_account_id : null,
      lastVerifiedAt: row ? row.last_verified_at : null,
      lastError: row ? row.last_error : null,
      isIssue: row ? ISSUE_STATES.has(row.state) : false,
    };
  });
}

export async function handleAdConnectionsGet(req, res, supabaseRequest = defaultSupabaseRequest) {
  const connections = await adConnectionsShape('ghgrp', supabaseRequest);
  res.status(200).json({ ok: true, connections });
}
export async function handleAdConnectionTransitionPost(req, res, supabaseRequest = defaultSupabaseRequest) {
  const b = req.body || {};
  const platform = String(b.platform || '').trim();
  const toState = String(b.toState || '').trim();
  const note = (b.note === null || b.note === undefined) ? null : (String(b.note).trim().slice(0, 500) || null);

  if (!AD_PLATFORMS.has(platform)) {
    return res.status(400).json({ ok: false, error: 'platform must be one of: ' + [...AD_PLATFORMS].join(', ') + '.' });
  }
  if (!CONNECTION_STATES.includes(toState)) {
    return res.status(400).json({ ok: false, error: 'toState must be one of: ' + CONNECTION_STATES.join(', ') + '.' });
  }

  const exRes = await supabaseRequest('ad_platform_connections?tenant_id=eq.ghgrp&platform=eq.' + encodeURIComponent(platform) + '&select=id,state,last_verified_at&limit=1');
  if (!exRes.ok) return res.status(500).json({ ok: false, error: await exRes.text() });
  const existing = await exRes.json();
  const fromState = existing[0] ? existing[0].state : 'not_connected';

  if (!isValidConnectionTransition(fromState, toState)) {
    return res.status(409).json({
      ok: false,
      error: 'Cannot move ' + platform + ' from ' + fromState + ' to ' + toState + ' -- that skips required steps in the connect/verify-reporting/verify-draft/enable-launch sequence.',
      fromState,
    });
  }

  const now = new Date().toISOString();
  const payload = {
    state: toState,
    updated_at: now,
    last_verified_at: ISSUE_STATES.has(toState) ? (existing[0] ? existing[0].last_verified_at : null) : now,
    last_error: ISSUE_STATES.has(toState) ? (note || ('Moved to ' + toState + '.')) : null,
  };

  const envVarName = String(b.envVarName || '').trim() || ('AD_' + platform.toUpperCase() + '_CONNECTION');
  const saveRes = existing.length
    ? await supabaseRequest('ad_platform_connections?tenant_id=eq.ghgrp&platform=eq.' + encodeURIComponent(platform), {
        method: 'PATCH', headers: { Prefer: 'return=minimal' },
        body: JSON.stringify(payload),
      })
    : await supabaseRequest('ad_platform_connections', {
        method: 'POST', headers: { Prefer: 'return=minimal' },
        body: JSON.stringify([{ tenant_id: 'ghgrp', platform, env_var_name: envVarName, ...payload }]),
      });
  if (!saveRes.ok) return res.status(500).json({ ok: false, error: await saveRes.text() });

  const connections = await adConnectionsShape('ghgrp', supabaseRequest);
  res.status(200).json({ ok: true, platform, fromState, toState, connections });
}
export async function handleAdCampaignsGet(req, res, supabaseRequest = defaultSupabaseRequest) {
  const platform = req.query && req.query.platform;
  const status = req.query && req.query.status;
  let query = 'ad_campaigns?tenant_id=eq.ghgrp&select=*&order=created_at.desc';
  if (platform) query += '&platform=eq.' + encodeURIComponent(platform);
  if (status) query += '&status=eq.' + encodeURIComponent(status);
  const listRes = await supabaseRequest(query);
  if (!listRes.ok) return res.status(500).json({ ok: false, error: await listRes.text() });
  const campaigns = await listRes.json();
  res.status(200).json({ ok: true, campaigns });
}
// The pure core of drafting an ad campaign, extracted so it has exactly one
// implementation. api/growth.js accepts a growth suggestion by calling this
// directly rather than re-deriving grounding facts or re-implementing the
// copy-generation fallback -- an accepted suggestion and a hand-drafted
// campaign must produce an identical row.
//
// Returns { ok: true, campaign } or { ok: false, status, error }. Refusals
// are returned, not thrown, because "AI copy is not configured" and "that
// division does not exist" are ordinary answers, not exceptions.
export async function createAdCampaignDraft(input, deps = {}) {
  const supabaseRequest = deps.supabaseRequest || defaultSupabaseRequest;
  const platform = String(input.platform || '').trim();
  const objective = String(input.objective || '').trim();
  const division = String(input.division || '').trim();
  const dailyBudgetCents = Number.isFinite(Number(input.dailyBudgetCents)) ? Math.round(Number(input.dailyBudgetCents)) : null;
  const manualCopy = (input.adCopy && typeof input.adCopy === 'object') ? input.adCopy : null;

  if (!AD_PLATFORMS.has(platform)) {
    return { ok: false, status: 400, error: 'platform must be one of: ' + [...AD_PLATFORMS].join(', ') + '.' };
  }
  if (!AD_OBJECTIVES.has(objective)) {
    return { ok: false, status: 400, error: 'objective must be one of: ' + [...AD_OBJECTIVES].join(', ') + '.' };
  }
  if (!KNOWN_DIVISIONS.includes(division)) {
    return { ok: false, status: 400, error: 'division must be one of: ' + KNOWN_DIVISIONS.join(', ') + '.' };
  }
  if (dailyBudgetCents === null || dailyBudgetCents < 0) {
    return { ok: false, status: 400, error: 'dailyBudgetCents must be a non-negative number.' };
  }

  const [divisionFacts, territoryFacts] = await Promise.all([
    realDivisionJobFacts(division, supabaseRequest),
    realServiceTerritoryFacts(supabaseRequest),
  ]);

  let adCopy = null;
  if (manualCopy) {
    const requiredKeys = ['headline', 'primaryText', 'description', 'cta'];
    for (const k of requiredKeys) {
      if (typeof manualCopy[k] !== 'string' || !manualCopy[k].trim()) {
        return { ok: false, status: 400, error: 'adCopy.' + k + ' is required when providing manual copy.' };
      }
    }
    adCopy = {
      headline: manualCopy.headline.trim(),
      primaryText: manualCopy.primaryText.trim(),
      description: manualCopy.description.trim(),
      cta: manualCopy.cta.trim(),
    };
  } else if (isAdCopyGenerationConfigured(deps)) {
    try {
      adCopy = await generateAdCopy({ platform, objective, division, divisionFacts, territoryFacts }, deps);
    } catch (e) {
      if (e.notConfigured) return { ok: false, status: 409, error: e.message };
      return { ok: false, status: 502, error: e.message };
    }
  } else {
    return { ok: false, status: 409, error: 'ANTHROPIC_API_KEY is not set for this deployment -- provide adCopy manually or configure AI generation.' };
  }

  const name = division + ' ' + objective.replace('_', ' ') + ' -- ' + platform;
  const payload = {
    tenant_id: 'ghgrp',
    platform,
    objective,
    name,
    status: 'draft',
    daily_budget_cents: dailyBudgetCents,
    targeting_summary: { division, divisionFacts, territoryFacts },
    ad_copy: adCopy,
    created_by: input.createdBy || 'reina',
  };
  const insertRes = await supabaseRequest('ad_campaigns', {
    method: 'POST', headers: { Prefer: 'return=representation' },
    body: JSON.stringify([payload]),
  });
  if (!insertRes.ok) return { ok: false, status: 500, error: await insertRes.text() };
  const [inserted] = await insertRes.json();
  return { ok: true, campaign: inserted };
}

export async function handleAdCampaignDraftPost(req, res, deps = {}) {
  const result = await createAdCampaignDraft(req.body || {}, deps);
  if (!result.ok) return res.status(result.status).json({ ok: false, error: result.error });
  res.status(200).json({ ok: true, campaign: result.campaign });
}
export async function handleAdCampaignReviewPost(req, res, supabaseRequest = defaultSupabaseRequest) {
  const b = req.body || {};
  const campaignId = String(b.campaignId || '').trim();
  const decision = String(b.decision || '').trim();
  if (!campaignId) return res.status(400).json({ ok: false, error: 'campaignId is required.' });
  if (decision !== 'approve' && decision !== 'reject') {
    return res.status(400).json({ ok: false, error: 'decision must be "approve" or "reject".' });
  }

  const campRes = await supabaseRequest('ad_campaigns?id=eq.' + encodeURIComponent(campaignId) + '&select=*&limit=1');
  if (!campRes.ok) return res.status(500).json({ ok: false, error: await campRes.text() });
  const [campaign] = await campRes.json();
  if (!campaign) return res.status(404).json({ ok: false, error: 'Campaign not found.' });
  if (campaign.status !== 'draft') {
    return res.status(409).json({ ok: false, error: 'This campaign is already "' + campaign.status + '" -- it can only be reviewed while in draft.' });
  }

  if (decision === 'reject') {
    const reason = b.reason ? String(b.reason).trim().slice(0, 2000) : null;
    const patchRes = await supabaseRequest('ad_campaigns?id=eq.' + encodeURIComponent(campaignId), {
      method: 'PATCH', headers: { Prefer: 'return=minimal' },
      body: JSON.stringify({ status: 'rejected', rejection_reason: reason, updated_at: new Date().toISOString() }),
    });
    if (!patchRes.ok) return res.status(500).json({ ok: false, error: await patchRes.text() });
    return res.status(200).json({ ok: true, campaignId, status: 'rejected' });
  }

  const budgetCheck = await checkBudgetHeadroom('ghgrp', campaign.daily_budget_cents || 0, { supabaseRequest });
  if (!budgetCheck.allowed) {
    return res.status(409).json({ ok: false, error: 'Cannot approve -- budget check failed: ' + budgetCheck.reason + '.', budgetCheck });
  }
  const actorEmail = (req.hlUser && req.hlUser.email) || 'owner';
  const patchRes = await supabaseRequest('ad_campaigns?id=eq.' + encodeURIComponent(campaignId), {
    method: 'PATCH', headers: { Prefer: 'return=minimal' },
    body: JSON.stringify({ status: 'pending_review', approved_by: actorEmail, approved_at: new Date().toISOString(), updated_at: new Date().toISOString() }),
  });
  if (!patchRes.ok) return res.status(500).json({ ok: false, error: await patchRes.text() });
  res.status(200).json({ ok: true, campaignId, status: 'pending_review', budgetCheck });
}

// ---------- per-platform launch/pause/spend-sync dispatch ----------
//
// Meta, Google Ads, and TikTok each get their own adapter call +
// external-id shape, but share the exact same guard clauses, budget check,
// error classification/connection-recording, and DB update pattern. Rather
// than duplicating that scaffolding per platform (as a first, Meta-only
// pass did), platformAdapters below is the single place that changes when
// the next platform goes live.
const platformAdapters = {
  meta: {
    launch: (deps) => deps.launchMetaCampaign || defaultLaunchMetaCampaign,
    pause: (deps) => deps.pauseMetaCampaign || defaultPauseMetaCampaign,
    spendSync: (deps) => deps.syncMetaCampaignSpend || defaultSyncMetaCampaignSpend,
    classifiedErrorKey: 'metaClassified',
  },
  google_ads: {
    launch: (deps) => deps.launchGoogleAdsCampaign || defaultLaunchGoogleAdsCampaign,
    pause: (deps) => deps.pauseGoogleAdsCampaign || defaultPauseGoogleAdsCampaign,
    spendSync: (deps) => deps.syncGoogleAdsCampaignSpend || defaultSyncGoogleAdsCampaignSpend,
    classifiedErrorKey: 'googleAdsClassified',
  },
  tiktok: {
    launch: (deps) => deps.launchTikTokCampaign || defaultLaunchTikTokCampaign,
    pause: (deps) => deps.pauseTikTokCampaign || defaultPauseTikTokCampaign,
    spendSync: (deps) => deps.syncTikTokCampaignSpend || defaultSyncTikTokCampaignSpend,
    classifiedErrorKey: 'tiktokClassified',
  },
};

function classifiedFromError(platform, e) {
  const key = platformAdapters[platform].classifiedErrorKey;
  return e[key] || { state: 'needs_attention', reason: platform + '_unclassified_error', message: e.message };
}

export async function handleAdCampaignLaunchPost(req, res, deps = {}) {
  const supabaseRequest = deps.supabaseRequest || defaultSupabaseRequest;
  const b = req.body || {};
  const campaignId = String(b.campaignId || '').trim();
  if (!campaignId) return res.status(400).json({ ok: false, error: 'campaignId is required.' });

  const campRes = await supabaseRequest('ad_campaigns?id=eq.' + encodeURIComponent(campaignId) + '&select=*&limit=1');
  if (!campRes.ok) return res.status(500).json({ ok: false, error: await campRes.text() });
  const [campaign] = await campRes.json();
  if (!campaign) return res.status(404).json({ ok: false, error: 'Campaign not found.' });
  if (campaign.status !== 'pending_review') {
    return res.status(409).json({ ok: false, error: 'This campaign is "' + campaign.status + '" -- it can only be launched after approval (pending_review).' });
  }
  if (!LIVE_PLATFORMS.has(campaign.platform)) {
    return res.status(409).json({ ok: false, error: 'Real launch is only wired up for ' + livePlatformLabelsText() + ' so far -- ' + campaign.platform + ' is still step 5.' });
  }
  if (!campaign.ad_copy) {
    return res.status(409).json({ ok: false, error: 'Campaign has no ad copy -- cannot launch.' });
  }

  const connRes = await supabaseRequest('ad_platform_connections?tenant_id=eq.ghgrp&platform=eq.' + encodeURIComponent(campaign.platform) + '&select=*&limit=1');
  if (!connRes.ok) return res.status(500).json({ ok: false, error: await connRes.text() });
  const [connection] = await connRes.json();
  if (!connection || connection.state !== 'launch_enabled') {
    return res.status(409).json({
      ok: false,
      error: AD_PLATFORM_LABELS[campaign.platform] + ' connection is not launch_enabled yet (' + (connection ? connection.state : 'not_connected') + ') -- complete the connect/verify sequence first.',
    });
  }

  const conn = resolvePlatformConn(campaign.platform, connection, { forLaunch: true });
  if (!conn) {
    return res.status(409).json({
      ok: false,
      error: AD_PLATFORM_LABELS[campaign.platform] + ' setup is not fully complete yet -- Chris still needs to finish adding its real credentials.',
    });
  }

  const budgetCheck = await checkBudgetHeadroom('ghgrp', campaign.daily_budget_cents || 0, { supabaseRequest });
  if (!budgetCheck.allowed) {
    return res.status(409).json({ ok: false, error: 'Cannot launch -- budget check failed: ' + budgetCheck.reason + '.', budgetCheck });
  }

  const launchFn = platformAdapters[campaign.platform].launch(deps);
  let launchResult;
  try {
    launchResult = await launchFn(
      { campaign, adCopy: campaign.ad_copy, conn, linkUrl: b.linkUrl || 'https://ghgrp.net' },
      deps.fetchImpl
    );
  } catch (e) {
    const classified = classifiedFromError(campaign.platform, e);
    if (isValidConnectionTransition(connection.state, classified.state)) {
      await supabaseRequest('ad_platform_connections?tenant_id=eq.ghgrp&platform=eq.' + encodeURIComponent(campaign.platform), {
        method: 'PATCH', headers: { Prefer: 'return=minimal' },
        body: JSON.stringify({ state: classified.state, last_error: classified.message || e.message, updated_at: new Date().toISOString() }),
      });
    }
    return res.status(502).json({ ok: false, error: AD_PLATFORM_LABELS[campaign.platform] + ' launch failed: ' + (classified.message || e.message), classified });
  }

  const patchRes = await supabaseRequest('ad_campaigns?id=eq.' + encodeURIComponent(campaignId), {
    method: 'PATCH', headers: { Prefer: 'return=minimal' },
    body: JSON.stringify({
      status: 'active',
      external_campaign_id: launchResult.externalCampaignId,
      updated_at: new Date().toISOString(),
    }),
  });
  if (!patchRes.ok) return res.status(500).json({ ok: false, error: await patchRes.text() });

  res.status(200).json({ ok: true, campaignId, status: 'active', launchResult });
}

export async function handleAdCampaignPausePost(req, res, deps = {}) {
  const supabaseRequest = deps.supabaseRequest || defaultSupabaseRequest;
  const b = req.body || {};
  const campaignId = String(b.campaignId || '').trim();
  if (!campaignId) return res.status(400).json({ ok: false, error: 'campaignId is required.' });

  const campRes = await supabaseRequest('ad_campaigns?id=eq.' + encodeURIComponent(campaignId) + '&select=*&limit=1');
  if (!campRes.ok) return res.status(500).json({ ok: false, error: await campRes.text() });
  const [campaign] = await campRes.json();
  if (!campaign) return res.status(404).json({ ok: false, error: 'Campaign not found.' });
  if (!LIVE_PLATFORMS.has(campaign.platform)) {
    return res.status(409).json({ ok: false, error: 'Real pause is only wired up for ' + livePlatformLabelsText() + ' so far -- ' + campaign.platform + ' is still step 5.' });
  }
  if (campaign.status !== 'active') {
    return res.status(409).json({ ok: false, error: 'This campaign is "' + campaign.status + '" -- only an active campaign can be paused.' });
  }
  if (!campaign.external_campaign_id) {
    return res.status(409).json({ ok: false, error: 'Campaign has no external_campaign_id -- it was never actually launched on ' + AD_PLATFORM_LABELS[campaign.platform] + '.' });
  }

  const connRes = await supabaseRequest('ad_platform_connections?tenant_id=eq.ghgrp&platform=eq.' + encodeURIComponent(campaign.platform) + '&select=*&limit=1');
  if (!connRes.ok) return res.status(500).json({ ok: false, error: await connRes.text() });
  const [connection] = await connRes.json();
  const conn = resolvePlatformConn(campaign.platform, connection);
  if (!conn) {
    return res.status(409).json({ ok: false, error: AD_PLATFORM_LABELS[campaign.platform] + ' connection has no usable credentials yet -- cannot pause this campaign.' });
  }

  // reason is accepted and echoed back for the caller's own audit trail --
  // there is no dedicated pause-reason column on ad_campaigns (that would
  // be a fabricated field), so it is not persisted to the database.
  const reason = b.reason ? String(b.reason).trim().slice(0, 2000) : null;
  const pauseFn = platformAdapters[campaign.platform].pause(deps);
  try {
    await pauseFn(campaign.external_campaign_id, conn, deps.fetchImpl);
  } catch (e) {
    const classified = classifiedFromError(campaign.platform, e);
    if (isValidConnectionTransition(connection.state, classified.state)) {
      await supabaseRequest('ad_platform_connections?tenant_id=eq.ghgrp&platform=eq.' + encodeURIComponent(campaign.platform), {
        method: 'PATCH', headers: { Prefer: 'return=minimal' },
        body: JSON.stringify({ state: classified.state, last_error: classified.message || e.message, updated_at: new Date().toISOString() }),
      });
    }
    return res.status(502).json({ ok: false, error: AD_PLATFORM_LABELS[campaign.platform] + ' pause failed: ' + (classified.message || e.message), classified });
  }

  const patchRes = await supabaseRequest('ad_campaigns?id=eq.' + encodeURIComponent(campaignId), {
    method: 'PATCH', headers: { Prefer: 'return=minimal' },
    body: JSON.stringify({ status: 'paused', updated_at: new Date().toISOString() }),
  });
  if (!patchRes.ok) return res.status(500).json({ ok: false, error: await patchRes.text() });

  res.status(200).json({ ok: true, campaignId, status: 'paused', reason });
}

export async function handleAdSpendSyncPost(req, res, deps = {}) {
  const supabaseRequest = deps.supabaseRequest || defaultSupabaseRequest;
  const b = req.body || {};
  const campaignId = String(b.campaignId || '').trim();
  if (!campaignId) return res.status(400).json({ ok: false, error: 'campaignId is required.' });

  const dateStr = b.date ? String(b.date).trim() : new Date().toISOString().slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
    return res.status(400).json({ ok: false, error: 'date must be in YYYY-MM-DD format.' });
  }

  const campRes = await supabaseRequest('ad_campaigns?id=eq.' + encodeURIComponent(campaignId) + '&select=*&limit=1');
  if (!campRes.ok) return res.status(500).json({ ok: false, error: await campRes.text() });
  const [campaign] = await campRes.json();
  if (!campaign) return res.status(404).json({ ok: false, error: 'Campaign not found.' });
  if (!LIVE_PLATFORMS.has(campaign.platform)) {
    return res.status(409).json({ ok: false, error: 'Real spend sync is only wired up for ' + livePlatformLabelsText() + ' so far -- ' + campaign.platform + ' is still step 5.' });
  }
  if (!campaign.external_campaign_id) {
    return res.status(409).json({ ok: false, error: 'Campaign has no external_campaign_id -- it was never actually launched on ' + AD_PLATFORM_LABELS[campaign.platform] + ', so there is no real spend to sync.' });
  }

  const connRes = await supabaseRequest('ad_platform_connections?tenant_id=eq.ghgrp&platform=eq.' + encodeURIComponent(campaign.platform) + '&select=*&limit=1');
  if (!connRes.ok) return res.status(500).json({ ok: false, error: await connRes.text() });
  const [connection] = await connRes.json();
  const conn = resolvePlatformConn(campaign.platform, connection);
  if (!conn) {
    return res.status(409).json({ ok: false, error: AD_PLATFORM_LABELS[campaign.platform] + ' connection has no usable credentials yet -- cannot sync spend.' });
  }

  const spendSyncFn = platformAdapters[campaign.platform].spendSync(deps);
  let syncResult;
  try {
    syncResult = await spendSyncFn(campaign.external_campaign_id, conn, dateStr, deps.fetchImpl);
  } catch (e) {
    const classified = classifiedFromError(campaign.platform, e);
    if (isValidConnectionTransition(connection.state, classified.state)) {
      await supabaseRequest('ad_platform_connections?tenant_id=eq.ghgrp&platform=eq.' + encodeURIComponent(campaign.platform), {
        method: 'PATCH', headers: { Prefer: 'return=minimal' },
        body: JSON.stringify({ state: classified.state, last_error: classified.message || e.message, updated_at: new Date().toISOString() }),
      });
    }
    return res.status(502).json({ ok: false, error: AD_PLATFORM_LABELS[campaign.platform] + ' spend sync failed: ' + (classified.message || e.message), classified });
  }

  const upsertRes = await supabaseRequest('ad_spend_ledger?on_conflict=tenant_id,platform,ad_campaign_id,spend_date', {
    method: 'POST',
    headers: { Prefer: 'resolution=merge-duplicates,return=representation' },
    body: JSON.stringify([{
      tenant_id: 'ghgrp',
      platform: campaign.platform,
      ad_campaign_id: campaignId,
      spend_date: syncResult.date,
      spend_cents: syncResult.spendCents,
      reported_at: new Date().toISOString(),
    }]),
  });
  if (!upsertRes.ok) return res.status(500).json({ ok: false, error: await upsertRes.text() });
  const [ledgerRow] = await upsertRes.json();

  res.status(200).json({ ok: true, campaignId, date: syncResult.date, spendCents: syncResult.spendCents, ledgerRow });
}

export default async function handler(req, res) {
  const resource = req.query.resource;

  const user = await requireUser(req);
  if (!user) {
    return res.status(401).json({ ok: false, error: 'Not authenticated. Sign in and try again.' });
  }
  req.hlUser = user;

  try {
    if (resource === 'ad_connections' && req.method === 'GET') {
      return await handleAdConnectionsGet(req, res);
    }
    if (resource === 'ad_connection_transition' && req.method === 'POST') {
      return await handleAdConnectionTransitionPost(req, res);
    }
    if (resource === 'ad_campaigns' && req.method === 'GET') {
      return await handleAdCampaignsGet(req, res);
    }
    if (resource === 'ad_campaign_draft' && req.method === 'POST') {
      return await handleAdCampaignDraftPost(req, res);
    }
    if (resource === 'ad_campaign_review' && req.method === 'POST') {
      return await handleAdCampaignReviewPost(req, res);
    }
    if (resource === 'ad_campaign_launch' && req.method === 'POST') {
      return await handleAdCampaignLaunchPost(req, res);
    }
    if (resource === 'ad_campaign_pause' && req.method === 'POST') {
      return await handleAdCampaignPausePost(req, res);
    }
    if (resource === 'ad_spend_sync' && req.method === 'POST') {
      return await handleAdSpendSyncPost(req, res);
    }
    return res.status(404).json({ ok: false, error: 'Unknown resource: ' + resource });
  } catch (e) {
    return res.status(500).json({ ok: false, error: e.message });
  }
}
